### ISSUE TITLE
'async_forward_entry_setup' deprecated

### ISSUE THREAD

**Issue by bryf2** [arturzx/homeassistant-iqua-softener#20]
### HA OS 2025.6

Error setting up entry iQua XXXXXXXXXX for iqua_softener
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iqua_softener/__init__.py", line 20, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, "sensor")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by jonmos75** [comment]
I am also getting this same error after updating to 2025.6 on HA OS

**Comment by kimbergirl** [comment]
same after updating to 2025.6 on HA OS

**Comment by bryf2** [comment]
This repo has not been updated in a few years so I attempted to resolve on my own. Seems to work.

Please "vi" and "dd" all lines of the init file. Then copy/paste ALL lines from this post. Reboot HA and it should work.

### **/homeassistant/custom_components/iqua_softener/\_\_init\_\_.py**
```python

import logging

from homeassistant import config_entries, core

from .const import DOMAIN

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[str] = ["sensor"]

async def async_setup_entry(hass: core.HomeAssistant, entry: config_entries.ConfigEntry) -> bool:

    hass.data.setdefault(DOMAIN, {})
    hass_data = dict(entry.data)
    unsub_options_update_listener = entry.add_update_listener(options_update_listener)
    hass_data["unsub_options_update_listener"] = unsub_options_update_listener
    hass.data[DOMAIN][entry.entry_id] = hass_data

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    return True


async def options_update_listener(
    hass: core.HomeAssistant, entry: config_entries.ConfigEntry
):
    await hass.config_entries.async_reload(config_entry.entry_id)


async def async_unload_entry(
    hass: core.HomeAssistant, entry: config_entries.ConfigEntry
) -> bool:
    unload_ok = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)

    hass.data[DOMAIN][entry.entry_id]["unsub_options_update_listener"]()

    if unload_ok:
        hass.data[DOMAIN].pop(entry.entry_id)

    return unload_ok
```

**Comment by Gierade** [comment]
@bryf2, could you please write exactly what needs to be changed in the code for the integration to start working again? 
Because after modifying the code fragments you provided, the configuration error still occurs.

**Comment by bryf2** [comment]
All I had to do was edit the Python init file and restart home assistant. I realized my original post does not have the underscores. Now corrected.

/homeassistant/custom_components/iqua_softener/\_\_init\_\_.py


If that still does not work try this:

1. Delete iQua integration through the Integration UI
2. rm -fr /homeassistant/custom_components/iqua_softener*
3. Restart HA
4. Redownload iQua integration through HACS
5. Add iQua Integration
6. Edit \_\_init\_\_.py file again and replace all lines with mine
7. Restart HA

Another separate issue I found long ago is the sensor.py file was edited in Windows (Ctrl M). So you may need to "dos2unix" that file to remove the ^M at the end of each line.


Here is my HASS Info

Installation method:  Home Assistant OS
Core:   2025.6.0
Supervisor:   2025.05.5
Operating System:   15.2
Frontend:   20250531.2

**Comment by kimbergirl** [comment]
tried.... didnt work for me

**Comment by jonmos75** [comment]
Thanks, @bryf2 What you posted got mine to work, but I saw my code was slightly different from yours. Once I made these changes, it is now not giving an error and it's pulling data. 

In the image below are the things I had to change from what I had. 

- First green box that says PLATFORMS: list[str] = ["sensor"] was missing from my coding. So I added that in the same location that he showed.

In doing so, I saw further down in @bryf2 code where is said **PLATFORMS** mine said **"sensor"** 
That told me that wherever I had the code **"sensor"** I would need to replace it with **PLATFORMS**. 

- The second green box I copied and pasted over my line of code and needed to delete this above it. For others, if you just copy and past all of his 1st code block you will not have to delete the code I did. 

- Last green box is where I needed just to change **"sensor"** to PLATFORMS

Once I made those three changes and checked that it would not cause HA to restart and then restarted HA. Once HA came back up, there were no more errors and was getting data from this integration.

I hope this helps others, as I am a newbie at this as well. 


  
![Image](https://github.com/user-attachments/assets/8cccf33d-f559-4221-accf-6e838e9436ba)

**Comment by kimbergirl** [comment]
tried.... still no luck

**Comment by Gierade** [comment]
Big thanks to @bryf2 and @jonmos75 for the support!
Thanks to your guidance I managed to get the integration working.

I'm attaching the full code in a file — it's easier to copy from there.

[plik.txt](https://github.com/user-attachments/files/20744539/plik.txt)

**Comment by maciejka104** [comment]
@Gierade @bryf2 @jonmos75 
Could you share whole zip archive with the integration?
I am trying to edit file(s) but I am still getting an error message.

I am one step ahead since @Gierade  shared file but now I am stuck at the next screen 

![Image](https://github.com/user-attachments/assets/2fe8c2b3-5ebf-4e9e-95f1-96b728919909)
ENG: 
Integration failed to load, try restarting Home Assistant.
Configuration created for iQua xxxxxx

logs:
Setup failed for custom integration 'iqua_softener': No setup or config entry setup function defined.

**Comment by kimbergirl** [comment]
Thanks @Gierade ... I finally got it to work as well!

**Comment by alexbeatle** [comment]
> Big thanks to [@bryf2](https://github.com/bryf2) and [@jonmos75](https://github.com/jonmos75) for the support! Thanks to your guidance I managed to get the integration working.
> 
> I'm attaching the full code in a file — it's easier to copy from there.
> 
> [plik.txt](https://github.com/user-attachments/files/20744539/plik.txt)
Easy-peesy, copy-paste, thank you!

Thank for the solution! No need to redo integration. Did the copy-paste of the code in the init file, save, reboot HASS, wait for the pull delay, back in business.

**Comment by bryf2** [comment]
> Big thanks to [@bryf2](https://github.com/bryf2) and [@jonmos75](https://github.com/jonmos75) for the support! Thanks to your guidance I managed to get the integration working.
> 
> I'm attaching the full code in a file — it's easier to copy from there.
> 
> [plik.txt](https://github.com/user-attachments/files/20744539/plik.txt)

Thanks for posting it in a text file @Gierade !

**Comment by bryf2** [comment]
> [@Gierade](https://github.com/Gierade) [@bryf2](https://github.com/bryf2) [@jonmos75](https://github.com/jonmos75) Could you share whole zip archive with the integration? I am trying to edit file(s) but I am still getting an error message.
> 
> I am one step ahead since [@Gierade](https://github.com/Gierade) shared file but now I am stuck at the next screen
> 
> ![Image](https://github.com/user-attachments/assets/2fe8c2b3-5ebf-4e9e-95f1-96b728919909) ENG: Integration failed to load, try restarting Home Assistant. Configuration created for iQua xxxxxx
> 
> logs: Setup failed for custom integration 'iqua_softener': No setup or config entry setup function defined.

You may need to remove the integration through the UI, delete the folder via CLI, restart HA, and then redownload the integration via HACS. Restart HA and then update the init file. Mine had issues once during troubleshooting due to trial and error with some of the other files.

**Comment by maciejka104** [comment]
@bryf2 
Did it several times. Checked SN few times (DSN#). 
Integation works .. error message when I enter username, password and Serial Number SL00235E271407
Application is connected. 
No idea what could be the problem.

**Comment by bryf2** [comment]
> [@bryf2](https://github.com/bryf2) Did it several times. Checked SN few times (DSN#). Integation works .. error message when I enter username, password and Serial Number SL00235E271407 Application is connected. No idea what could be the problem.


Check this file:  /homeassistant/custom_components/iqua_softener/sensor.py

If you have ^M at the end of each line run this command on it and restart HA. This file passes DSN and credentials.

dos2unix sensor.py

**Comment by maciejka104** [comment]
@bryf2 
problem solved!
Didn't see any ^M but dos2unix solved problem.
Thank you!

**Comment by jeremyloman** [comment]
Thank you so much.  This solved my problem as well.

**Comment by dtylerlivingston** [comment]
@bryf2 _init_.py file worked for me.  I just copied and pasted over my existing file without making any changes.  However I needed to modify sensor.py after receiving this message:
```

Logger: homeassistant.components.sensor

Source: components/sensor/__init__.py:573

integration: Sensor (documentation, issues)

First occurred: 1:28:30 PM (1 occurrence)

Last logged: 1:28:30 PM

Entity sensor.water_usage_daily_average (<class 'custom_components.iqua_softener.sensor.IquaSoftenerWaterUsageDailyAverageSensor'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/arturzx/homeassistant-iqua-softener/issues
```

to fix I simply commented out line 135 

<img width="416" height="123" alt="Image" src="https://github.com/user-attachments/assets/ce5b77e1-c53c-4e1d-a311-a5eb6ae724c6" />

After restarting HA, all worked.
